service: stat-buddy-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-west-2'
  timeout: 280
  stage: prod

functions:
  events:
    handler: src/events/handler.crawl
    events:
      - schedule: cron(0/1 * * * ? *)
  profiles:
    handler: src/profiles/handler.crawl
    events:
      - schedule: cron(0/1 * * * ? *)
