service: stat-buddy-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: 'us-west-2'
  timeout: 280
  stage: prod
  environment:
    REGION: ${self:provider.region}
  vpc:
    securityGroupIds:
      - sg-06e6016270b7ba7be
    subnetIds:
      - subnet-01da18b7c2c643779
      - subnet-00068135d8086f24b
      - subnet-0f1ea28ebfe78ede2
      - subnet-0fa6cee5cc8efa95c

functions:
  events:
    handler: src/events/handler.crawl
    events:
      - schedule: cron(0/5 * * * ? *)
  profiles:
    handler: src/profiles/handler.crawl
    events:
      - schedule: cron(0/5 * * * ? *)
