service: stat-buddy-serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-west-2'
  timeout: 280
  stage: prod

functions:
  events:
    handler: src/api/events/handler.get
    events:
      - http:
          path: events
          method: get
          cors: true
  games:
    handler: src/jobs/games/handler.crawl
    events:
      - schedule: cron(0/1 * * * ? *)
  profiles:
    handler: src/jobs/profiles/handler.crawl
    events:
      - schedule: cron(0/1 * * * ? *)
