service: stat-buddy-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: 'us-west-2'
  timeout: 280
  stage: prod
  environment:
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:198547082312:table/*"

functions:
  crawl:
    handler: src/crawler/handler.crawl
    events:
      - schedule: cron(0/5 * * * ? *)
  export:
    handler: src/export/handler.export
    events:
      - schedule: cron(0/5 * * * ? *)
