module.exports = {
  Hit: 'HIT',
  Hittee: 'HITTEE',
  BlockedShot: 'BLOCKED_SHOT',
  ShotBlocked: 'SHOT_BLOCKED',
  MissedShot: 'MISSED_SHOT',
  Shot: 'SHOT',
  Save: 'SAVE',
  Faceoff: 'FACEOFF',
  FaceoffLoss: 'FACEOFF_LOSS',
  Penalty: 'PENALTY',
  PenaltyDrawn: 'PENALTY_DRAWN',
  Goal: 'GOAL',
  GoalAllowed: 'GOAL_ALLOWED',
  Assist: 'ASSIST',
  Takeaway: 'TAKEAWAY',
  Giveaway: 'GIVEAWAY',
  GameScheduled: 'GAME_SCHEDULED',
  Away: 'AWAY',
  Home: 'HOME',
  GoalieType: 'Goalie',
  GoalieRelief: 'X',
  FightingPenaltyType: 'Fighting',
  RegularGameType: 'R',
  PlayoffGameType: 'P',
  AllStarGameType: 'A',
  PreSeasonGameType: 'PR',
};
