module.exports = {
  Hit: 'HIT',
  Hittee: 'HITTEE',
  BlockedShot: 'BLOCKED_SHOT',
  ShotBlocked: 'SHOT_BLOCKED',
  Shot: 'SHOT',
  Save: 'SAVE',
  Faceoff: 'FACEOFF',
  FaceoffLoss: 'FACEOFF_LOSS',
  Penalty: 'PENALTY',
  PenaltyDrawn: 'PENALTY_DRAWN',
  Goal: 'GOAL',
  GoalAllowed: 'GOAL_ALLOWED',
  Assist: 'ASSIST',
  Takeaway: 'TAKEAWAY',
  Giveaway: 'GIVEAWAY',
  Away: 'AWAY',
  Home: 'HOME',
  GoalieType: 'Goalie',
};
